name: Security Scan

on:
  push:
    branches: [ master,develop ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ master,develop ]
  schedule:
    - cron: '0 0 * * 2'
  workflow_dispatch:

jobs:
 scanjob:
   name: Security Scan Job
   uses: postmanlabs/gh-security-scan-workflow/.github/workflows/security.yml@v1.0
   secrets: inherit
   with:
    imagename: postman-sdk-go
    language: "['go']"